[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cp -r dist ../backend/public",
  "cd backend && npm install"
]

[start]
cmd = "cd backend && npm run migrate && npm start"
